# Change these first
owner: raquelinca
repo: Raquelpractica1

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Sitio Roto de Prueba
    url: https://pruebasitiorroto.xyz

status-website:
  # cname: demo.upptime.js.org
  baseUrl: /Raquelpractica1
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/raquelinca/Raquelpractica1). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/raquelinca/Raquelpractica1
# Upptime también soporta notificaciones, asignación de issues, y más
# Ver https://upptime.js.org/docs/configuration
